import argparse
import ast
from attrdict import AttrDict

def get_args_from_input():
	parser = argparse.ArgumentParser(description='modify network parameters', argument_default=argparse.SUPPRESS)

	parser.add_argument('--learning_rate', metavar='', type=float, help='learning rate')
	parser.add_argument('--max_epochs', metavar='', type=int, help='maximum number of epochs for training')
	parser.add_argument('--layer_type', metavar='', help='type of layer in GNN (GCN, GIN, GAT, etc.)')
	parser.add_argument('--display', metavar='', type=bool, help='toggle display messages showing training progress')
	parser.add_argument('--device', metavar='', type=str, help='name of CUDA device to use or CPU')
	parser.add_argument('--eval_every', metavar='X', type=int, help='calculate validation/test accuracy every X epochs')
	parser.add_argument('--stopping_criterion', metavar='', type=str, help='model stops training when this criterion stops improving (can be train, validation, or test)')
	parser.add_argument('--stopping_threshold', metavar='T', type=float, help="model perceives no improvement when it does worse than (best loss) * T")
	parser.add_argument('--patience', default=30, metavar='P', type=int, help='model stops training after P epochs with no improvement')
	parser.add_argument('--train_fraction', metavar='', type=float, help='fraction of the dataset to be used for training')
	parser.add_argument('--validation_fraction', metavar='', type=float, help='fraction of the dataset to be used for validation')
	parser.add_argument('--test_fraction', metavar='', type=float, help='fraction of the dataset to be used for testing')
	parser.add_argument('--dropout', metavar='', type=float, help='layer dropout probability')
	parser.add_argument('--weight_decay', metavar='', type=float, help='weight decay added to loss function')
	parser.add_argument('--hidden_dim', metavar='', type=int, help='width of hidden layer')
	parser.add_argument('--hidden_layers', metavar='', type=ast.literal_eval, help='list containing dimensions of all hidden layers')
	parser.add_argument('--num_layers', metavar='', type=int, help='number of hidden layers')
	parser.add_argument('--batch_size', default=16, metavar='', type=int, help='number of samples in each training batch')
	parser.add_argument('--num_trials', default=30, metavar='', type=int, help='number of times the network is trained'),
	parser.add_argument('--rewiring', metavar='', type=str, help='type of rewiring to be performed'),
	parser.add_argument('--num_iterations', metavar='', type=int, help='number of iterations of rewiring')
	parser.add_argument('--alpha', type=float, help='alpha hyperparameter for DIGL')
	parser.add_argument('--k', type=int, help='k hyperparameter for DIGL')
	parser.add_argument('--eps', type=float, help='epsilon hyperparameter for DIGL')
	parser.add_argument('--dataset', type=str, help='name of dataset to use')
	parser.add_argument('--last_layer_fa', type=str, help='whether or not to make last layer fully adjacent')
	parser.add_argument('--logfile', default='graph_classification_fa.csv', type=str, help='file name(under results dir) to record the results')
	parser.add_argument('--sample', type=bool, help='if sample for nnpr rewiring method(useful for large graph)')
	parser.add_argument('--scale', type=float, help='sample number for one node = scale * degree of the node')
	parser.add_argument('--save', type=bool, help='if to save the model trained')
        parser.add_argument('--prop', type=int, help='which propertry to regress')
        parser.add_argument('--dataset_root', type=str, help='root directory where datasets are stored')
        parser.add_argument('--qm9_radius', type=float, help='cutoff radius (in Å) used to build QM9 radius graphs')
        parser.add_argument('--qm9_max_neighbors', type=int, help='maximum number of neighbors to keep per node in QM9 graphs')
        parser.add_argument('--train_size', type=int, help='number of training samples to use from QM9')
        parser.add_argument('--val_size', type=int, help='number of validation samples to use from QM9')
        parser.add_argument('--test_size', type=int, help='number of test samples to use from QM9')
        parser.add_argument('--num_workers', type=int, help='number of worker processes for data loading')
        parser.add_argument('--seed', type=int, help='random seed for QM9 experiments')
        arg_values = parser.parse_args()
        return AttrDict(vars(arg_values))
